# Generated by Django 5.2.1 on 2026-06-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='annual_leave_balance',
            field=models.DecimalField(decimal_places=1, default=20, max_digits=4),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='sick_leave_balance',
            field=models.DecimalField(decimal_places=1, default=12, max_digits=4),
        ),
    ]
